<h2><center>Assignment 5</center></h2>
<h3><center>Programming for Data Science 2026</center></h3>
<b><center>Deadline: 14:00, April 2, 2026</center></b>

- The exercise will be marked as **passed** if you get **at least 10/16** points.

- Exercises must be handed in via **ILIAS** (Homework assignments). Submit your work as a **compressed (.zip)** file containing **one** `.py` **or** `.ipynb` file with **all exercises**.

- The name of **both** the `.zip` file and the `.py`/`.ipynb` file must be the *SurnameName* of the **two group members**, separated by an underscore.  
  Example: Tim Tabellen and Lara Lambda → `TabellenTim_LambdaLara.zip`  
  (The `.py`/`.ipynb` file must have the same name.)

- Use **comments** to explain your code and demonstrate that you understand the solutions and can discuss them.

- You are not expected to collaborate outside your group. Submitting other groups’ code as your own will result in **0 points**.

- For general questions about the lecture content, assignments, or the exam, please use the **ILIAS forum**.

- For individual questions about lecture content and the exam, contact: *roland.widmer@students.unibe.ch*  

- For individual questions about the exercises or grading, contact: *julien.brunner@students.unibe.ch* or *aline.steiner@students.unibe.ch*

#### Exercise 1: Pandas DataFrame from scratch *(2.5 points)*

1. Create a DataFrame *mountains_df* with the columns **name**, **height**, and **first_ascent**, as below:

|**name**|**height**|**first_ascent**|
|:---|:---|:---|
|Mont Blanc|46950|1786|
|Monte Rosa|4634|1855|
|Grande Ruine|3765|1873|
|Piz Sena|3075|1901|

Do not specify a specific column as an index.

In [1]:
# TODO

2. Sort `mountains_df` by first_ascent in descending order and store it in `sorted_mountains_df`. Then explain the difference between `.iloc[0]` and `.loc[0]` on this sorted DataFrame.

In [2]:
# TODO

**Your answer**: TODO

3. Correct the height of Mont Blanc by replacing the incorrect value `46950` with the correct value `4695` in the DataFrame Use an indexing approach that clearly identifies the correct row, then briefly explain your choice.

In [3]:
# TODO

**Your answer**: TODO

4. Print all rows of `mountains_df` where the first ascent was between 1800 and 1900 (inclusive).

In [4]:
# TODO

5. Create a new column `height_feet` and calculate the height in feet using vectorized operations (no loops) and the following identity:

$1 \mathrm{ft} = 3.280839895 \mathrm{m}$

In [5]:
# TODO

#### Exercise 2: Names I *(3 points)*

We start with two pandas Series that contain fictional counts of selected names in Bern and Zurich.

In [6]:
import pandas as pd

names_bern = pd.Series(
    [110, 160, 160],
    index=["Anna", "Ben", "Clara"]
)

names_zurich = pd.Series(
    [100, 70, 170],
    index=["Anna", "Clara", "David"]
)

1. Add them together to get the combined count of the names in Bern and Zurich and store the Series in `names_combined`. Missing names in a single Series should be treated as 0. Use appropriate pandas methods and print the result. 

Hint: The argument `fill_value` might be helpful

In [8]:
# TODO

2. Print `names_combined` sorted by name (ascending).

In [9]:
# TODO

3. Print the most frequent name.

Hint: use a method that works like `argmax` but works on the labels.

In [10]:
# TODO

#### Exercise 3: Names II *(4 points)*

The dataset for this exercise contains the counts of first names of the population by gender for the years 2024 and 2016.

Source: [Federal Statistical Office](https://www.bfs.admin.ch/bfs/en/home/statistics/population/births-deaths/names-switzerland.assetdetail.36062343.html)

Note: For privacy reasons, names with counts lower than 3 were counted as `0`.

1. Load the CSV file `data/csv/names.csv` as a dataframe `first_names_df`.

In [11]:
# TODO

2. Create a new column `total` containing the sum of the male and female counts.

In [12]:
# TODO

3. For the year 2024, calculate the the percentage of distinct names whose total count is below 100 (i.e., percentage of rare first names).

In [13]:
# TODO

4. Which 5 names had the biggest increase in 2024 compared to 2016?

Hint: create a pandas Series per year. Exercise 2 might help you.

In [14]:
# TODO

#### Exercise 4: Spotify *(4 points)*

1. Load `data/csv/spotify_songs.csv` as a pandas DataFrame.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/csv/spotify_songs.csv')

2. Count the number of missing values in each column and drop the rows with the missing values. Store the cleaned DataFrame in `spotify_df_clean`.

In [35]:
df.isna().sum()
spotify_df_clean = df.dropna()

3. Find the songs with the best rank (`daily_rank`, i.e., the lowest) on the 17.02.2025 (`snapshot_date`). Print the song name and the artist and the country in which the song had lowest rank.

In [50]:
ranked = spotify_df_clean[spotify_df_clean['snapshot_date'] == '2025-02-17'].sort_values(by='daily_rank', ascending=True)
ranked.tail(1)[['name', 'country']]

             name country
3587  Abracadabra      AE

4. Map the country abbreviations to the full country names (e.g., ZA -> South Africa) and store the country name in a new column `country_name`.

In [54]:
country_dict = {
    'ZA': 'South Africa',
    'VN': 'Vietnam',
    'VE': 'Venezuela',
    'UY': 'Uruguay',
    'US': 'United States',
    'UA': 'Ukraine',
    'TW': 'Taiwan',
    'TR': 'Turkey',
    'TH': 'Thailand',
    'SV': 'El Salvador',
    'SK': 'Slovakia',
    'SG': 'Singapore',
    'SE': 'Sweden',
    'SA': 'Saudi Arabia',
    'RO': 'Romania',
    'PY': 'Paraguay',
    'PT': 'Portugal',
    'PL': 'Poland',
    'PK': 'Pakistan',
    'PH': 'Philippines',
    'PE': 'Peru',
    'PA': 'Panama',
    'NZ': 'New Zealand',
    'NO': 'Norway',
    'NL': 'Netherlands',
    'NI': 'Nicaragua',
    'NG': 'Nigeria',
    'MY': 'Malaysia',
    'MX': 'Mexico',
    'MA': 'Morocco',
    'LV': 'Latvia',
    'LU': 'Luxembourg',
    'LT': 'Lithuania',
    'KZ': 'Kazakhstan',
    'KR': 'South Korea',
    'JP': 'Japan',
    'IT': 'Italy',
    'IS': 'Iceland',
    'IN': 'India',
    'IL': 'Israel',
    'IE': 'Ireland',
    'ID': 'Indonesia',
    'HU': 'Hungary',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'GT': 'Guatemala',
    'GR': 'Greece',
    'FR': 'France',
    'FI': 'Finland',
    'ES': 'Spain',
    'EG': 'Egypt',
    'EE': 'Estonia',
    'EC': 'Ecuador',
    'DO': 'Dominican Republic',
    'DK': 'Denmark',
    'DE': 'Germany',
    'CZ': 'Czech Republic',
    'CR': 'Costa Rica',
    'CO': 'Colombia',
    'CL': 'Chile',
    'CH': 'Switzerland',
    'CA': 'Canada',
    'BY': 'Belarus',
    'BR': 'Brazil',
    'BO': 'Bolivia',
    'BG': 'Bulgaria',
    'BE': 'Belgium',
    'AU': 'Australia',
    'AT': 'Austria',
    'AR': 'Argentina',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom'
}

spotify_df_clean['country_name'] = spotify_df_clean['country'].map(country_dict)

spotify_df_clean[['country', 'country_name']]

     country  country_name
50        ZA  South Africa
51        ZA  South Africa
52        ZA  South Africa
53        ZA  South Africa
54        ZA  South Africa
...      ...           ...
9995      DK       Denmark
9996      DK       Denmark
9997      DK       Denmark
9998      DK       Denmark
9999      DK       Denmark

[9850 rows x 2 columns]

#### Exercise 5: Distances *(4 points)*

In this exercise, we want to calculate the distances from Bern to other cities in the world.

Source: [https://simplemaps.com/data/world-cities](https://simplemaps.com/data/world-cities)

1. Load the `data/csv/worldcities.csv` using pandas and store it in the variable `cities_df`.

In [ ]:
import pandas as pd
import numpy as np

cities_df = pd.read_csv("../data/csv/worldcities.csv")

2. For the next task, we need the latitude and longitude in radians instead of degrees. Create new columns `lat_rad` and `lng_rad` with the converted value in radians.

Hint: Use the suitable NumPy Ufunc.

In [ ]:
cities_df['lat_rad'] = np.deg2rad(cities_df.lat)
cities_df['lng_rad'] = np.deg2rad(cities_df.lng)

cities_df

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,lat_rad,lng_rad
0,Tokyo,Tokyo,35.6870,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764,0.622856,2.439089
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077,-0.107774,1.864492
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604,0.499339,1.347918
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133,0.403695,1.976760
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629,0.332941,1.271952
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48054,Al Jabīn,Al Jabin,14.7040,43.5990,Yemen,YE,YEM,Raymah,admin,NaN,1887910100,0.256633,0.760946
48055,Nelspruit,Nelspruit,-25.4745,30.9703,South Africa,ZA,ZAF,Mpumalanga,admin,NaN,1710114438,-0.444614,0.540534
48056,Gqeberha,Gqeberha,-33.9681,25.5981,South Africa,ZA,ZAF,Eastern Cape,NaN,NaN,1710000082,-0.592855,0.446771
48057,Lupane,Lupane,-18.9315,27.8070,Zimbabwe,ZW,ZWE,Matabeleland North,admin,NaN,1716206606,-0.330417,0.485324
48058,Charlotte Amalie,Charlotte Amalie,18.3420,-64.9331,U.S. Virgin Islands,VI,VIR,Virgin Islands,primary,NaN,1850037473,0.320128,-1.133296

2. Calculate the distance between Bern and all the cities in a new column `distance_to_bern`. You can do this by using the Haversine formula:

$$ d = r \cdot 2 \cdot \arcsin \left( \sqrt{\sin^2 \left( \frac{lat2 - lat1}{2}\right) + \cos(lat1) \cdot \cos(lat2) \cdot \sin^2 \left( \frac{lng2 - lng1}{2}\right)} \right), $$

where $lat1$ and $lat2$ are the latitudes in radians, and $lng1$ and $lng2$ the longitudes in radians, and the $r$ the radius of the Earth. 

Hints:
- For Bern, use lat=46.94798°, lng=7.44743° and $r=6371 km$. The calculated distances will be in kilometers.
- Do not forget to convert the coordinates of Bern to radians.
- There are many suitable Ufuncs to use, e.g., `np.arcsin`.

In [17]:
be_lat = np.deg2rad(46.94798)
be_lng = np.deg2rad(7.44743)

cities_df['distance_to_bern'] = 6371 * 2 * np.arcsin(np.sqrt(np.sin((cities_df.lat_rad - be_lat)/2)**2 + np.cos(be_lat)*np.cos(cities_df.lat_rad)*(np.sin((cities_df.lng_rad - be_lng)/2)**2)))

In [ ]:
# cities_df[cities_df['city'] == 'Rome']

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,lat_rad,lng_rad,distance_to_bern
289,Rome,Rome,41.8931,12.4828,Italy,IT,ITA,Lazio,primary,2748109.0,1380382862,0.731173,0.217866,689.489635
14416,Rome,Rome,34.2662,-85.1863,United States,US,USA,Georgia,NaN,37754.0,1840014681,0.598058,-1.486781,7486.172514
16807,Rome,Rome,43.2260,-75.4909,United States,US,USA,New York,NaN,31795.0,1840000349,0.754436,-1.317565,6208.275278

3. Does your code use broadcasting? If yes, indicate where.

**Your answer**: 
It does use broadcasting when getting the ditance_to_bern calculations since for each value in the column lat_rad it subtracts it to a single value be_lat that repeats itself as much as needed to match all the values for the calculation.

4. Sort the dataframe by your calculated distances, such that the lowest distance to Bern is the first row. Print the first 7 rows of the sorted dataframe.

In [27]:
cities_df.sort_values(by='distance_to_bern')[0:7]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,lat_rad,lng_rad,distance_to_bern
4641,Bern,Bern,46.9480,7.4474,Switzerland,CH,CHE,Bern,primary,134506.0,1756374318,0.819397,0.129982,0.003183
27138,Ostermundigen,Ostermundigen,46.9553,7.4833,Switzerland,CH,CHE,Bern,NaN,17751.0,1756779389,0.819525,0.130608,2.841717
34076,Muri,Muri,46.9319,7.4872,Switzerland,CH,CHE,Bern,NaN,13054.0,1756349869,0.819116,0.130676,3.509044
13163,Köniz,Koniz,46.9250,7.4153,Switzerland,CH,CHE,Bern,NaN,41784.0,1756022220,0.818996,0.129421,3.532753
37369,Belp,Belp,46.8914,7.4972,Switzerland,CH,CHE,Bern,NaN,11510.0,1756855405,0.818409,0.130851,7.339616
43767,Wohleiberg,Wohleiberg,46.9719,7.3569,Switzerland,CH,CHE,Bern,NaN,9281.0,1756011124,0.819814,0.128402,7.367343
37820,Worb,Worb,46.9306,7.5644,Switzerland,CH,CHE,Bern,NaN,11311.0,1756060343,0.819093,0.132024,9.088315